name: windows-arm64

on:
  push:
    branches:
      - test-v1.23.2-2
      - crt-win
  workflow_dispatch:
    inputs:
      version:
        description: "Version information (e.g., 1.23.2)"
        required: true

permissions:
  contents: write

env:
  ONNXRUNTIME_VERSION:
    |- # Enter release tag name or version name in workflow_dispatch. Appropriate version if not specified
    ${{ github.event.release.tag_name || github.event.inputs.version || '1.23.2' }}

jobs:
  windows_arm64:
    name: ${{ matrix.os }} static CRT ${{ matrix.use_static_crt }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022]
        python-version: ["3.10"]
        use_static_crt: ["ON", "OFF"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache build result for ${{ env.ONNXRUNTIME_VERSION }}
        id: cache-build-result
        uses: actions/cache@v4
        with:
          path: onnxruntime-win-arm64-static_lib-static-crt-${{ matrix.use_static_crt }}-${{ env.ONNXRUNTIME_VERSION }}
          key: onnxruntime-win-arm64-static-crt-${{ matrix.use_static_crt }}-${{ env.ONNXRUNTIME_VERSION }}-cache-v1

      - name: ccache
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ matrix.os }}-arm64

      - name: Update ONNX Runtime
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo ${{ env.ONNXRUNTIME_VERSION }} > ONNXRUNTIME_VERSION
          git submodule update --init --depth=1 onnxruntime
          cd onnxruntime
          git fetch origin tag v${{ env.ONNXRUNTIME_VERSION }}
          git checkout v${{ env.ONNXRUNTIME_VERSION }}

          if [[ ${{ env.ONNXRUNTIME_VERSION }} =~ 1.16.[0-9] ]]; then
            sed -i.bak '13d' onnxruntime/core/platform/windows/stacktrace.cc
            git status
            git diff
          fi

      - name: Download protoc
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          # see ./cmake/deps.txt
          if [[ ${{ env.ONNXRUNTIME_VERSION }} =~ 1.14.[0-9] ]]; then
            curl -SL -o protoc-3.20.3-win64.zip https://github.com/protocolbuffers/protobuf/releases/download/v3.20.3/protoc-3.20.3-win64.zip
            ls -lh
            file protoc-3.20.3-win64.zip
            unzip protoc-3.20.3-win64.zip
          elif [[ ${{ env.ONNXRUNTIME_VERSION }} =~ 1.1[56789].[0-9] || ${{ env.ONNXRUNTIME_VERSION }} =~ 1.2[0-9].[0-9] ]]; then
            curl -SL -o protoc-21.12-win64.zip https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-win64.zip
            ls -lh
            file protoc-21.12-win64.zip
            unzip protoc-21.12-win64.zip
          else
            echo "Unsupported version ${{ env.ONNXRUNTIME_VERSION }}"
            exit 1
          fi
          rm -fv protoc*.zip

          ./bin/protoc --version

      - name: Set environment variable
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "$GITHUB_WORKSPACE/bin"  >> "$GITHUB_PATH"
          echo $GITHUB_WORKSPACE

      - name: Display protoc info for ${{ env.ONNXRUNTIME_VERSION }}
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          protoc --version

      - name: Show current directory
        shell: bash
        run: |
          ls -lh
          echo $PWD

      - name: Install dependencies
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python3 -m pip install cmake
          cmake --version

      - name: Build onnxruntime for Windows arm64
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          export CMAKE_CXX_COMPILER_LAUNCHER=ccache
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cmake --version
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"

          echo "$GITHUB_WORKSPACE/bin/protoc"
          # /D/a/onnxruntime-build/onnxruntime-build/bin/protoc
          /D/a/onnxruntime-build/onnxruntime-build/bin/protoc --version

          use_static_crt=${{ matrix.use_static_crt }}

          if [[ $use_static_crt == ON ]]; then
            export CMAKE_OPTIONS='-DUSE_STATIC_CRT=ON -Dgtest_force_shared_crt=OFF -A ARM64 -Donnxruntime_BUILD_UNIT_TESTS=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/D/a/onnxruntime-build/onnxruntime-build/bin/protoc.exe'
          else
            export CMAKE_OPTIONS='-DUSE_STATIC_CRT=OFF -Dgtest_force_shared_crt=ON -A ARM64 -Donnxruntime_BUILD_UNIT_TESTS=OFF -DONNX_CUSTOM_PROTOC_EXECUTABLE=/D/a/onnxruntime-build/onnxruntime-build/bin/protoc.exe'
          fi

          echo "CMAKE_OPTIONS: $CMAKE_OPTIONS"

          ./build-static_lib.sh

      - name: Collect result
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        shell: bash
        run: |
          ls -lh output/static_lib/
          ls -lh output/static_lib/include
          ls -lh output/static_lib/lib

          use_static_crt=${{ matrix.use_static_crt }}

          if [[ $use_static_crt == ON ]]; then
            dst=onnxruntime-win-arm64-static_lib-MT-${{ env.ONNXRUNTIME_VERSION }}
          else
            dst=onnxruntime-win-arm64-static_lib-MD-${{ env.ONNXRUNTIME_VERSION }}
          fi
          mkdir $dst
          mv -v output/static_lib/* $dst

      - name: zip results
        shell: bash
        run: |
          use_static_crt=${{ matrix.use_static_crt }}

          if [[ $use_static_crt == ON ]]; then
            dst=onnxruntime-win-arm64-static_lib-MT-${{ env.ONNXRUNTIME_VERSION }}
          else
            dst=onnxruntime-win-arm64-static_lib-MD-${{ env.ONNXRUNTIME_VERSION }}
          fi
          tar cjvf $dst.tar.bz2 $dst
          ls -lh

      - name: Upload v${{ env.ONNXRUNTIME_VERSION }}
        uses: svenstaro/upload-release-action@v2
        with:
          file_glob: true
          file: "./*.tar.bz2"
          overwrite: true
          repo_name: csukuangfj/onnxruntime-libs
          repo_token: ${{ secrets.UPLOAD_GH_SHERPA_ONNX_TOKEN }}
          tag: v${{ env.ONNXRUNTIME_VERSION }}

      - name: Publish to huggingface
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        uses: nick-fields/retry@v2
        with:
          max_attempts: 20
          timeout_seconds: 200
          shell: bash
          command: |
            git config --global user.email "csukuangfj@gmail.com"
            git config --global user.name "Fangjun Kuang"

            rm -rf huggingface
            export GIT_LFS_SKIP_SMUDGE=1
            export GIT_CLONE_PROTECTION_ACTIVE=false

            ls -lh

            git clone https://huggingface.co/csukuangfj2/onnxruntime-libs huggingface
            cd huggingface
            git pull

            use_static_crt=${{ matrix.use_static_crt }}

            if [[ $use_static_crt == ON ]]; then
              name=onnxruntime-win-arm64-static_lib-MT-${{ env.ONNXRUNTIME_VERSION }}.tar.bz2
            else
              name=onnxruntime-win-arm64-static_lib-MD-${{ env.ONNXRUNTIME_VERSION }}.tar.bz2
            fi

            version=${{ env.ONNXRUNTIME_VERSION }}
            mkdir -p $version

            cp -v ../$name $version/

            git status
            git add .
            git commit -m "add $name"
            git push https://csukuangfj2:$HF_TOKEN@huggingface.co/csukuangfj2/onnxruntime-libs main

      - uses: actions/upload-artifact@v4
        if: steps.cache-build-result.outputs.cache-hit != 'true'
        with:
          name: onnxruntime-win-arm64-static_lib-static-CRT-${{ matrix.use_static_crt }}
          path: onnxruntime-win-arm64-static_lib*.tar.bz2
